### ISSUE TITLE
Übersicht pops up when not wanted

### ISSUE THREAD

**Issue by ax42** [felixhageloh/uebersicht#141]
If I Ctrl-Click my desktop, I get a window which says "reload / Inspect element".  This is not so much a problem on the desktop, but if I Ctrl-click in Starcraft, Ubersicht takes focus and shows the same window, which makes gameplay very difficult.  Please fix / revert / make this an option.

**Comment by felixhageloh** [comment]
Sorry to hear! Does it still happen with version 0.6.19 released today?

**Comment by TRMman** [comment]
With version 0.6.19 I only get this pop-up when I ctrl-click with the trackpad on the desktop, not with a mouse. In the previous version this "reload / Inspect element" pop-up also appeared after a ctrl-click in other windows eg. the Finder.

**Comment by ax42** [comment]
It happens on 19 as well, but less obvious (clicking often makes it appear).  Happens with a mouse (G500, Logitech Game Drivers installed) and with a Magic Trackpad (1st generation, with BetterTouchTool running as well).  I also saw it happen in other windows before (v18), but now only seems to happen on the desktop.

**Comment by ax42** [comment]
Can confirm that this is no longer an issue for me in Starcraft (v19).  Still appears when one ^-clicks the desktop but that's a minor annoyance at best (I will hardly ever ^-click the desktop anyways).

**Comment by Omniscity** [comment]
Hello Felix,

My first post. Great software. But, as ax42 have said, this problem occurs with me as well. I am running OSX 10.10.5. This problem did not occur with Übersicht v. 0.5 as I can set the modifier key (I cannot see this option in the Übersicht menu anymore).

**Comment by felixhageloh** [comment]
@Omniscity can you also check whether you have the latest version (0.6.19)? The issue existed in 0.6 but should be fixed with 0.6.19

**Comment by everlearners** [comment]
I am still having this issue. I was unable to get a ctrl-click menu anywhere, but updated to 0.6.19 today, which eliminated the problem most places, but it still persists on the desktop. Example: https://youtu.be/Q2h9-YhkKo8

Quitting Übersicht eliminates the problem. Curiously, the problem happens on the iMac desktop but not on the external Thunderbolt display.

I am running OS X 10.11.1 El Cap on a 27 in Late 2013 iMac with a second Thunderbolt display.

**Comment by Omniscity** [comment]
@felixhageloh Thank you for the quick response... yes, I have the latest version. The issue still persists. Like @everlearners have said, quitting Übersicht eliminates the problem. Hmm........

**Comment by felixhageloh** [comment]
I've just released a new version (0.6.20) that should fix this!

**Comment by ax42** [comment]
Fixed for me now -- thanks!

**Comment by Omniscity** [comment]
@felixhageloh Fixed; thank you very much.

**Comment by felixhageloh** [comment]
Glad to hear it is fixed :). Thanks everyone for the thorough and polite bug reports!

**Comment by everlearners** [comment]
Perfect! Thank you so much!
