### ISSUE TITLE
both displays

### ISSUE THREAD

**Issue by wfalkwallace** [felixhageloh/uebersicht#32]
currently the menubar icon offers options for "show on built-in display" and "show on thunderbolt display" (or whatever the other display is) -- is it possible to add a "show on all displays" option? I think mirroring would be sufficient for this feature.

**Comment by StJohn3D** [comment]
+1 for choice of display on a per-widget basis. The Drag and drop branch might also solve this if we could easily drag widgets to our other displays like rainmeter on windows.

**Comment by felixhageloh** [comment]
I finally got around building this feature. Anyone interested in being a beta tester?

**Comment by MishimaHaruna** [comment]
I certainly am!

**Comment by felixhageloh** [comment]
here is a link https://dl.dropboxusercontent.com/u/49351082/%C3%9Cbersicht-0.8beta.app.zip
You can report any issues you find here!

**Comment by cros13** [comment]
> “Übersicht-0.8beta” is damaged and can’t be opened. You should move it to the Trash.

**Comment by felixhageloh** [comment]
I've updated the link (although the old one worked for me as well) https://dl.dropboxusercontent.com/u/49351082/Uebersicht-0.8beta.app.zip

**Comment by MishimaHaruna** [comment]
FWIW, the old one worked for me, depending on the software I used to extract it (Finder and The Unarchiver failed, WinZip succeeded)

I'm testing it and it looks very good for now (but then again, I haven't played with plugging and unplugging different screens yet, only using my main two for now). Out of curiosity, if I run the same widget on two screens at once, does the widget's command get called once or twice?

**Comment by cros13** [comment]
Yup... It was an extraction fail... unarchiver & finder.

**Comment by cros13** [comment]
Keka worked for extraction. Looks good so far...

**Comment by felixhageloh** [comment]
Odd - I just used the standard Finder compress function to create the zip. I am on a beta version of OSX tho ... anyway, it sounds like you got it working. 

@MishimaHaruna showing the same widget on several screens is not implemented yet actually. It should be easily possible but for some reason I did not have a use case for it. Is it something you'd like to have?

**Comment by MishimaHaruna** [comment]
@felixhageloh Then I just found a bug -- If I don't select any screens, widgets seem to default to all screens at once (and in the menu, it doesn't show any check mark next to them).

I think it could have its uses. I kept my analog clock widget on all screens because it defaulted to that, and it looked cool that way. If it's an easy thing to do, then I think it'd be nice -- otherwise I can just duplicate the widget's folder to achieve a similar result.

**Comment by felixhageloh** [comment]
@MishimaHaruna yup that was a bug - thanks! I think I fixed and I've updated the app (same link).
I'll think about adding 'all screens' as an option. It is doable of course but it makes the settings more complicated. I think I want to wait till I get more feedback to make a definite decision whether to add this feature or not.

**Comment by felixhageloh** [comment]
@cros13 @MishimaHaruna also let me know If you still have the same issues extracting the file. I'm worried the current stable version (0.7.24) also has the same issue. I've since installed The Unarchiver but it seems to extract it fine as well. Thanks again!

**Comment by MishimaHaruna** [comment]
For me it still shows the '“Übersicht-0.8beta 2.app” is damaged and can’t be opened. You should move it to the Trash.' message, if I extract it with Finder (Archive Utility) or The Unarchiver. Extracting it with Keka, Path Finder, StuffIt or WinZip, works fine.  According to Apple, the error message means that the app has been edited by something other than the developer (I assume it means the code sign verification fails). The other apps seem to remove the quarantine attribute when extracting archives coming from the internet, so GateKeeper is less strict with signature verification (or skips it altogether), and as such it runs.

**Comment by felixhageloh** [comment]
@MishimaHaruna I found the issue - I'm including a new framework that wasn't code signed correctly. I've updated the app link. 
I also changed the behavior based on your feedback. You can now show widgets on all screens, on the current main screen, or you can manually select which screens to show it on. 

Oh and you probably will have to run:
```
rm ~/Library/Application\ Support/tracesOf.Uebersicht/WidgetSettings.json
```

because your settings will be incompatible with this version

**Comment by MishimaHaruna** [comment]
@felixhageloh The current beta seems pretty good (thank you for adding the option to show on all screens!). I played a bit, connecting and disconnecting external displays, and I haven't run into any issues so far.
I confirm it now works correctly after extracting with Finder or The Unarchiver (it shows the normal prompt "This app was downloaded from the Internet", offering the option to run it)

**Comment by felixhageloh** [comment]
Awesome thanks! There is a new version out with some UI tweaks and fixes - feel free to check it out :) (same link again)

**Comment by felixhageloh** [comment]
This has been added with the 0.8 release!
